//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSmsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public partial class SmsRequestDto : object
    {
        
        private string ApplicationNameField;
        
        private System.Nullable<System.DateTime> ExpireDateField;
        
        private string MessageTextField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        private string ServicePasswordField;
        
        private RCSmsService.SmsSendDto[] SmsSendListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpireDate
        {
            get
            {
                return this.ExpireDateField;
            }
            set
            {
                this.ExpireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText
        {
            get
            {
                return this.MessageTextField;
            }
            set
            {
                this.MessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServicePassword
        {
            get
            {
                return this.ServicePasswordField;
            }
            set
            {
                this.ServicePasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCSmsService.SmsSendDto[] SmsSendList
        {
            get
            {
                return this.SmsSendListField;
            }
            set
            {
                this.SmsSendListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendDto", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public partial class SmsSendDto : object
    {
        
        private string ErrorMessageField;
        
        private string MessageIdField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsResponseDto", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public partial class SmsResponseDto : object
    {
        
        private bool IsSentToAgentField;
        
        private string RcSMSServiceMessageField;
        
        private RCSmsService.SmsServiceReturnCodeType RcSMSServiceReturnCodeField;
        
        private RCSmsService.SmsSendDto[] SmsReceivedListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSentToAgent
        {
            get
            {
                return this.IsSentToAgentField;
            }
            set
            {
                this.IsSentToAgentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RcSMSServiceMessage
        {
            get
            {
                return this.RcSMSServiceMessageField;
            }
            set
            {
                this.RcSMSServiceMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCSmsService.SmsServiceReturnCodeType RcSMSServiceReturnCode
        {
            get
            {
                return this.RcSMSServiceReturnCodeField;
            }
            set
            {
                this.RcSMSServiceReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCSmsService.SmsSendDto[] SmsReceivedList
        {
            get
            {
                return this.SmsReceivedListField;
            }
            set
            {
                this.SmsReceivedListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsServiceReturnCodeType", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public enum SmsServiceReturnCodeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectCharacterPhone = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEmptyPhoneNumber = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNullPhoneNumber = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectCharacterSms = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LengthSms = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEmptySms = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNullSms = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEmptyMessageId = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotNullMessageId = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectLogin = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsServiceClose = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceError = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedCmd = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUser = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOriginator = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXml = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMessageId = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InsufficientFunds = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPhoneNumber = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoNotHaveTheAuthorityTo = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LockedTheCustomer = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForTheInstallationOfCredit = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubmissionWaitingTime = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToBeSentToSmscy = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendToSmscy = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReachedTheReceiver = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeSentToTheRecipient = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DidNotReachTheRecipient = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFoundMessageInSmscd = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFoundMessageInServer = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThisMessageDoesNotBelongToYou = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepetitionOfTheMessageSoDeleted = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeadlineIsInvalidSoDeleted = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RefusedBySmscSoDeleted = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectPhoneNumberSoDeleted = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsToLengtSoDeleted = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimCardChangeSoDeleted = -6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeoutSoDeleted = -7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InsufficientCreditSoDeleted = -8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToTheBlockedMessageSoDeleted = -9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletedMessageByCustomer = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillDebtSoDeleted = -11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMobileNumberSoDeleted = -12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnkownError = 999,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsStatusDto", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public partial class SmsStatusDto : object
    {
        
        private string CoreStatusField;
        
        private string MessageIdField;
        
        private RCSmsService.SmsStatusType RCStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoreStatus
        {
            get
            {
                return this.CoreStatusField;
            }
            set
            {
                this.CoreStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCSmsService.SmsStatusType RCStatus
        {
            get
            {
                return this.RCStatusField;
            }
            set
            {
                this.RCStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsStatusType", Namespace="http://schemas.datacontract.org/2004/07/SimpleSMSWcf")]
    public enum SmsStatusType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RCSmsService.IRcSmsService")]
    public interface IRcSmsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRcSmsService/SendSms", ReplyAction="http://tempuri.org/IRcSmsService/SendSmsResponse")]
        System.Threading.Tasks.Task<RCSmsService.SmsResponseDto> SendSmsAsync(RCSmsService.SmsRequestDto dtoSmsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRcSmsService/GetStatus", ReplyAction="http://tempuri.org/IRcSmsService/GetStatusResponse")]
        System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetStatusAsync(RCSmsService.SmsStatusDto[] messageIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRcSmsService/GetCoreStatus", ReplyAction="http://tempuri.org/IRcSmsService/GetCoreStatusResponse")]
        System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetCoreStatusAsync(RCSmsService.SmsStatusDto[] messageIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRcSmsService/GetStatusLocal", ReplyAction="http://tempuri.org/IRcSmsService/GetStatusLocalResponse")]
        System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetStatusLocalAsync(RCSmsService.SmsStatusDto[] messageIdList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IRcSmsServiceChannel : RCSmsService.IRcSmsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class RcSmsServiceClient : System.ServiceModel.ClientBase<RCSmsService.IRcSmsService>, RCSmsService.IRcSmsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RcSmsServiceClient() : 
                base(RcSmsServiceClient.GetDefaultBinding(), RcSmsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRcSmsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RcSmsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RcSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), RcSmsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RcSmsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RcSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RcSmsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RcSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RcSmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RCSmsService.SmsResponseDto> SendSmsAsync(RCSmsService.SmsRequestDto dtoSmsRequest)
        {
            return base.Channel.SendSmsAsync(dtoSmsRequest);
        }
        
        public System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetStatusAsync(RCSmsService.SmsStatusDto[] messageIdList)
        {
            return base.Channel.GetStatusAsync(messageIdList);
        }
        
        public System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetCoreStatusAsync(RCSmsService.SmsStatusDto[] messageIdList)
        {
            return base.Channel.GetCoreStatusAsync(messageIdList);
        }
        
        public System.Threading.Tasks.Task<RCSmsService.SmsStatusDto[]> GetStatusLocalAsync(RCSmsService.SmsStatusDto[] messageIdList)
        {
            return base.Channel.GetStatusLocalAsync(messageIdList);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRcSmsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRcSmsService))
            {
                return new System.ServiceModel.EndpointAddress("http://smsservicetest.robcol.k12.tr/RcSmsService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RcSmsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRcSmsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RcSmsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRcSmsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRcSmsService,
        }
    }
}
